Backend changes
AntonBergaker/calviton pull request #15
Opened 2020-04-06 09:48 UTC by AntonBergaker

Backend navigator implementerad och refererbar i main. Inte ändrat vad frontend faktiskt använder.

2020-04-06 09:56 UTC, AntonBergaker commented
Vänta med att merga, några ändringar krävs

2020-04-07 06:11 UTC, AntonBergaker commented
Ok

2020-04-07 06:52 UTC, carlenlund commented
Hur är det tänkt att denna PR ska testas?

2020-04-07 07:01 UTC, AntonBergaker commented
> Hur är det tänkt att denna PR ska testas? Dvs så vi vet att allt fungerar.

Bön.
Får massa fel så behöver gå tillbaka och fixa, kan passa på att lägga till tester.

2020-04-07 07:59 UTC, AntonBergaker commented
La till tester å bytte namn på result till task för att bättre reflektera vad det är

2020-04-07 08:35 UTC, astridno approved these changes
Det fungerar bra, testen kör!

2020-04-07 08:49 UTC, carlenlund requested changes
Det ser rimligt ut, men jag vill gärna se hur detta kopplas till frontend.

Du får gärna implementera ändringarna i QML tillsammans med backend, så blir det tydligt hur allt fungerar ihop.
Eftersom ändringarna i din PR inte är knutet till andra delar av programmet som jag förstår det, tycker jag det är bäst om vi gör en hel "vertikal slice".

2020-04-14 09:58 UTC, AntonBergaker commented
![image](https://user-images.githubusercontent.com/12459883/79212025-472b0180-7e47-11ea-8120-c71eb587246d.png)

Tog ett tag, men funkar iaf

2020-04-14 11:16 UTC, arvidsandin approved these changes

2020-04-14 11:36 UTC, carlenlund approved these changes

2020-04-14 11:40 UTC, merged