Support offline maps
AntonBergaker/calviton pull request #28
Opened 2020-04-24 07:50 UTC by carlenlund

Appen kan nu använda sig av en offline map tile directory för att visa upp kartan.

Map tiles kan genereras på nytt genom att köra `./scripts/generate-tiles.sh`. Det är möjligt att ändra parametrar för vilka tiles som laddas ner genom att redigera scriptet.

GMapCatcher under `dependencies/gmapcatcher` gör det möjligt att ladda ner map tiles oför olika typer av kartor. När alla tiles är nedladdade används `./scripts/osm-tile-structure.sh` för att uppdatera mappstrukturen så att den går att använda av OpenStreetMap-pluginet till QtLocation. Allt detta görs automatiskt i `./scripts/generate-tiles.sh`.

2020-04-24 07:52 UTC, carlenlund commented on src/main.qml
> +        PluginParameter {
Gör att offline tiles används by default.

2020-04-24 07:53 UTC, carlenlund commented on scripts/generate-tiles.sh
> +$DIR/../dependencies/gmapcatcher/download.py \
Just nu genereras tiles för som mest större delen av Uppsala.

2020-04-24 13:02 UTC, carlenlund commented
Efter att ha tömt min map tile cache på datorn (under `~/.cache`) visar appen plötsligt en grå skärm för kartan. Jag ska undersöka vad detta kan bero på.

2020-04-27 09:28 UTC, carlenlund commented
![](https://github.trello.services/images/mini-trello-icon.png) [[5] Karta ska fungera offline](https://trello.com/c/O1w6ZRBA/35-5-karta-ska-fungera-offline)

2020-04-28 09:50 UTC, AntonBergaker requested changes
Sätter en request changes så den slutar stå som öppen

2020-05-04 07:46 UTC, closed without merging

2020-05-04 07:47 UTC, carlenlund commented
Börjar om på nytt på en ny branch för MapBox offline-kartor.