Prepare route optimization
AntonBergaker/calviton pull request #55
Opened 2020-05-13 09:17 UTC by carlenlund

2020-05-13 09:19 UTC, carlenlund commented
Just nu saknas kod för att faktiskt optimera själva rutten, men den bör vara fullt förbered med metoder och kodstruktur för implementera optimering.

2020-05-13 12:54 UTC, carlenlund commented
Just nu tar inte programmet hänsyn till var föraren startar sin navigering. Detta gör att man kan börja på fel sida av sin rutt. Detta behöver jag fixa.

2020-05-13 13:01 UTC, carlenlund commented
Jag ska lägga in error checking. Typ max 6 zoner.

2020-05-14 10:10 UTC, carlenlund commented
`Connections` verkar göra att hela appen kraschar just nu.

2020-05-21 10:00 UTC, AntonBergaker requested changes

2020-05-21 10:00 UTC, AntonBergaker commented on src/availableroutes.cpp
> +                Zone *zone2 = zones[j];
oklart vad 1/2 är. Döp till endZone och startZone?

2020-05-21 10:00 UTC, AntonBergaker commented on src/availableroutes.cpp
> +            NavigationTask *userZoneTask = new NavigationTask(this);
User?

2020-05-21 10:00 UTC, AntonBergaker commented on src/availableroutes.cpp
> +    Q_ASSERT(task->result() != nullptr);
Noice.

2020-05-21 10:00 UTC, AntonBergaker commented on src/availableroutes.cpp
> +void AvailableRoutes::OptimizeRoutesWithZoneDistances()
3 for loops i en funktion. Kanske kan flytta ut till en funktion som bara gör en route så blir det mindre tabs iaf?

2020-05-21 10:00 UTC, AntonBergaker commented on src/route.cpp
> +        }
Kanske sätt en tidig return här för att slippa else och så blir det mindre tabs

2020-05-21 11:20 UTC, carlenlund commented on src/availableroutes.cpp
> +            NavigationTask *userZoneTask = new NavigationTask(this);
Lägger till kommentar i header-filen om benämningen.

2020-05-21 11:38 UTC, AntonBergaker approved these changes
![image](https://user-images.githubusercontent.com/12459883/82555638-6a448180-9b68-11ea-91a5-fea800013288.png)

2020-05-21 11:39 UTC, merged