Map view shows directions of current route
AntonBergaker/calviton pull request #9
Opened 2020-04-01 12:46 UTC by arvidsandin

2020-04-01 13:03 UTC, carlenlund requested changes
Navigeringsvyn bör även visa nuvarande rutt/ruttbeskrivning.

Jag föreslår att mapvyn tas bort eftersom det kommer att finnas exakt samma innehåll på de olika vyerna. När vi lägger till turn-by-turn så får vi ha en knapp som sätter igång detta på navigeringsvyn.

2020-04-01 13:03 UTC, carlenlund commented on src/MapView.qml
> +                Text { text: hasManeuver ? modelData.maneuver.instructionText : ""; wrapMode:Text.Wrap;width:parent.width}
Bryt gärna properties på flera rader så blir det lättare att läsa.

2020-04-01 13:03 UTC, carlenlund commented on src/main.qml
> +        name: "osm"
Vi får undersöka vilka konsekvenser OSM vs MapBox ger. Känns rimligt att börja så här i nuläget i alla fall.

2020-04-02 06:44 UTC, AntonBergaker approved these changes
Ser bra ut, all info vi behöver är exposed. Det enda jag har att komma med är en nitpick om att RouteQuery kan flyttas in i RouteModel så den inte behöver ha ett namn.

2020-04-02 06:45 UTC, astridno commented on src/main.qml
> +        name: "osm"
mapboxglPluging -> osmPlugin så att det inte blir förvirrande, kanske måste använda mapboxgl oxå vid något tillfälle

2020-04-02 07:10 UTC, carlenlund approved these changes

2020-04-02 07:11 UTC, merged